core_bundle_club:
    resource: "@ARPCCoreBundle/Resources/config/routing_club.yml"
    prefix: /club
    
core_bundle_mail:
    resource: "@ARPCCoreBundle/Resources/config/routing_mail.yml"
    prefix: /mail
