security:
    encoders:
        ARPCCoreBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        main:
            entity:
             class: ARPCCoreBundle\Entity\Player
             property: ffeCode

    firewalls:
        main:
            pattern: ^/
            form_login:
                login_path: login
                check_path: login_check
            anonymous: true

            logout:
                path: /logout
                target: /