security:
    encoders:
        ARPCCoreBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        main:
            entity:
             class: ARPCCoreBundle\Entity\Player
             property: ffeCode

    firewalls:
        main:
            pattern:    ^/
            http_basic: ~
            provider: main