<?php

namespace ARPCCoreBundle\Repository;

/**
 * ClubRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClubRepository extends \Doctrine\ORM\EntityRepository
{
    public function findClubByCode($clubCode)
    {
        $qb = $this
            ->createQueryBuilder('club')
            ->where('club.code = :code')
            ->setParameter('code', $clubCode);
        
        return $qb->getQuery()->getSingleResult();
    }
}
