<?php

namespace ARPCCoreBundle\Repository;

/**
 * ContactWayRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactWayRepository extends \Doctrine\ORM\EntityRepository
{
}
