<?php

namespace ARPCCoreBundle\Repository;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllPlayersByClub($clubCode)
    {
        $qb = $this
            ->createQueryBuilder('player')
            ->join('player.club', 'club')
            ->addSelect('club')
            ->where('club.code = :code')
            ->setParameter('code', $clubCode);

        return $qb->getQuery()->getResult();
    }
}
