<?php

namespace ARPCCoreBundle\Repository;

/**
 * TeamEventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamEventRepository extends \Doctrine\ORM\EntityRepository
{
}
