<?php

namespace ARPCCoreBundle\Repository;

/**
 * TeamRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TeamRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllTeamsByClub($clubCode)
    {
        $qb = $this
            ->createQueryBuilder('team')
            ->join('team.club', 'club')
            ->addSelect('club')
            ->where('club.code = :code')
            ->setParameter('code', $clubCode);

        return $qb->getQuery()->getResult();
    }
}
