club_index:
    path:     /
    defaults: { _controller: ARPCCoreBundle:Club:index }

club_add:
    path:     /add
    defaults: { _controller: ARPCCoreBundle:Club:add }

club_players:
    path:     /players
    defaults: { _controller: ARPCCoreBundle:Club:players }

club_events:
    path:     /events
    defaults: { _controller: ARPCCoreBundle:Club:events }

club_teams:
    path:     /teams
    defaults: { _controller: ARPCCoreBundle:Club:teams }

club_edit:
    path:     /edit/{code}
    defaults: { _controller: ARPCCoreBundle:Club:edit }

club_show_id:
    path:     /{id}
    defaults: { _controller: ARPCCoreBundle:Club:showId }
    requirements:
        id: \d+

club_show:
    path:     /{code}
    defaults: { _controller: ARPCCoreBundle:Club:showCode }