services:
#    arpc_core.example:
#        class: ARPCCoreBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]

    arpc.environnement:
        class: ARPCCoreBundle\Services\Environnement\ARPCEnvironnement
        arguments: ['@security.authorization_checker','@security.token_storage']

    arpc.player_csv_import:
        class: ARPCCoreBundle\Services\Csv\PlayerCsvImport
        arguments: ['@doctrine.orm.entity_manager']
        
    arpc.sms_sender:
        class: ARPCCoreBundle\Services\SMS\SMSSender
        arguments:
